load("encode_raw_string_as_crate_name_test.bzl", "encode_raw_string_as_crate_name_test_suite")

package(
    default_testonly = 1,
)

encode_raw_string_as_crate_name_test_suite(name = "encode_raw_string_as_crate_name_tests")
