""" Contains version numbers to be used in other bzl files """
PROTOC_VERSION = "25.1"
PROTOBUF_JAVA_VERSION = "3.25.1"
PROTOBUF_PYTHON_VERSION = "4.25.1"
PROTOBUF_PHP_VERSION = "3.25.1"
PROTOBUF_RUBY_VERSION = "3.25.1"
