""" Contains version numbers to be used in other bzl files """
PROTOC_VERSION = "28.0-rc-3"
PROTOBUF_JAVA_VERSION = "4.28.0-RC3"
PROTOBUF_PYTHON_VERSION = "5.28.0rc3"
PROTOBUF_PHP_VERSION = "4.28.0RC3"
PROTOBUF_RUBY_VERSION = "4.28.0.rc.3"
