""" Contains version numbers to be used in other bzl files """
PROTOC_VERSION = "27.0-rc-1"
PROTOBUF_JAVA_VERSION = "4.27.0-RC1"
PROTOBUF_PYTHON_VERSION = "5.27.0rc1"
PROTOBUF_PHP_VERSION = "4.27.0RC1"
PROTOBUF_RUBY_VERSION = "4.27.0.rc.1"
