source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

install! 'cocoapods', :deterministic_uuids => false

if ENV['USE_FRAMEWORKS'] == 'YES' then
  use_frameworks!
end

target 'iOSCocoaPodsTester' do
  pod 'Protobuf', :path => '../../../..'
end
