# Copyright (c) 2009-2021, Google LLC
# All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

# begin:google_only
# load(
#     "//upb/bazel:build_defs.bzl",
#     "UPB_DEFAULT_CPPOPTS",
# )
#
# package(default_applicable_licenses = ["//upb:license"])
#
# licenses(["notice"])
#
# cc_library(
#     name = "protos",
#     hdrs = [
#         "protos.h",
#     ],
#     copts = UPB_DEFAULT_CPPOPTS,
#     visibility = ["//visibility:public"],
#     deps = [
#         "//hpb",
#         "//hpb/backend/upb:interop",
#     ],
# )
# end:google_only
