load(":proto_common_compile_tests.bzl", "proto_common_compile_test_suite")

package(default_applicable_licenses = ["//:license"])

proto_common_compile_test_suite(name = "proto_common_compile_test_suite")
