# Protocol Buffers - Google's data interchange format
# Copyright 2008 Google Inc.  All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

load("@com_google_protobuf//bazel:proto_library.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "any_proto",
    srcs = ["src/google/protobuf/any.proto"],
)

proto_library(
    name = "api_proto",
    srcs = ["src/google/protobuf/api.proto"],
    deps = [
        ":source_context_proto",
        ":type_proto",
    ],
)

proto_library(
    name = "descriptor_proto",
    srcs = ["src/google/protobuf/descriptor.proto"],
)

proto_library(
    name = "duration_proto",
    srcs = ["src/google/protobuf/duration.proto"],
)

proto_library(
    name = "empty_proto",
    srcs = ["src/google/protobuf/empty.proto"],
)

proto_library(
    name = "field_mask_proto",
    srcs = ["src/google/protobuf/field_mask.proto"],
)

proto_library(
    name = "source_context_proto",
    srcs = ["src/google/protobuf/source_context.proto"],
)

proto_library(
    name = "struct_proto",
    srcs = ["src/google/protobuf/struct.proto"],
)

proto_library(
    name = "timestamp_proto",
    srcs = ["src/google/protobuf/timestamp.proto"],
)

proto_library(
    name = "type_proto",
    srcs = ["src/google/protobuf/type.proto"],
    deps = [
        ":any_proto",
        ":source_context_proto",
    ],
)

proto_library(
    name = "wrappers_proto",
    srcs = ["src/google/protobuf/wrappers.proto"],
)
