[package]
edition = "2021"   # The Rust edition (not to be confused with Protobuf Edition).
name = "protobuf-codegen"
readme = "README.md"
version = "{PROTOBUF_LEGACY_VERSION}"
description = "Code generator for Rust Protocol Buffers bindings"
license = "BSD-3-Clause"
rust-version = "1.79"
# Superseded by the google-protobuf-codegen crate, which this crate re-exports.
# No new versions are published to crates.io.
publish = false

[dependencies]
google_protobuf_codegen = { package = "google-protobuf-codegen", version = "{PROTOBUF_RUST_VERSION}", path = "../google_protobuf_codegen" }
