[package]
name = "google-protobuf-well-known-types"
readme = "README.md"
version = "{PROTOBUF_RUST_VERSION}"
edition = "2021"
description = "Protobuf Well-Known Types"
license = "BSD-3-Clause"

[dependencies]
protobuf = { version = "{PROTOBUF_RUST_VERSION}", path = "../google_protobuf", package = "google-protobuf" }
protobuf-codegen = { version = "{PROTOBUF_RUST_VERSION}", path = "../google_protobuf_codegen", package = "google-protobuf-codegen" }
