module BasicTest
  class MessageContainerTest < Test::Unit::TestCase
    def proto_module: () -> singleton(BasicTest)
    include CommonTests

    def test_issue_8311_crash: () -> void
    def test_issue_8559_crash: () -> void
    def test_issue_9440: () -> void
    def test_issue_9507: () -> void
    def test_has_field: () -> void
    def test_no_presence: () -> void
    def test_set_clear_defaults: () -> void
    def test_import_proto2: () -> void
    def test_clear_repeated_fields: () -> void
    def test_initialization_map_errors: () -> void
    def test_map_field: () -> void
    def test_map_field_with_symbol: () -> void
    def test_map_inspect: () -> void
    def test_map_corruption: () -> void
    def test_map_wrappers: () -> void
    def test_map_wrappers_with_default_values: () -> void
    def test_map_wrappers_with_no_value: () -> void
    def test_concurrent_decoding: () -> void
    def test_map_encode_decode: () -> void
    def test_protobuf_decode_json_ignore_unknown_fields: () -> void
    #def test_json_quoted_string: () -> void
    def test_to_h: () -> void
    def test_json_maps: () -> void
    def test_json_maps_emit_defaults_submsg: () -> void
    def test_json_emit_defaults_submsg: () -> void
    def test_respond_to: () -> void
    def test_file_descriptor: () -> void
    def test_map_freeze: () -> void
    def test_map_length: () -> void
    def test_string_with_singleton_class_enabled: () -> void
    def test_utf8: () -> void
    def test_map_fields_respond_to?: () -> void
    def test_has_presence: () -> void
    def test_is_packed: () -> void
    def test_file_descriptor_options: () -> void
    def test_field_descriptor_options: () -> void
    def test_descriptor_options: () -> void
    def test_enum_descriptor_options: () -> void
    def test_oneof_descriptor_options: () -> void
    def test_nested_extension: () -> void
    def test_options_deep_freeze: () -> void
    def test_message_freeze: () -> void
  end

  def test_oneof_fields_respond_to?: () -> void
  def test_string_subclass: () -> void
end
