[package]
name = "staging-protobuf-example"
version = "{VERSION}"
edition = "2021"

[dependencies]
protobuf = { version = "{VERSION}", path = "../protobuf", package = "staging-protobuf" }

[build-dependencies]
protobuf-codegen = { version = "{VERSION}", path = "../protobuf_codegen", package = "staging-protobuf-codegen" }