// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: csharp/protos/unittest_deep_dependencies/file278.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UnittestDeepDependencies {

  /// <summary>Holder for reflection information generated from csharp/protos/unittest_deep_dependencies/file278.proto</summary>
  public static partial class File278Reflection {

    #region Descriptor
    /// <summary>File descriptor for csharp/protos/unittest_deep_dependencies/file278.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static File278Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjZjc2hhcnAvcHJvdG9zL3VuaXR0ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2Zp",
            "bGUyNzgucHJvdG8SGnVuaXR0ZXN0X2RlZXBfZGVwZW5kZW5jaWVzGid1bml0",
            "dGVzdF9kZWVwX2RlcGVuZGVuY2llcy9maWxlMTQucHJvdG8aJ3VuaXR0ZXN0",
            "X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGUyNC5wcm90bxoodW5pdHRlc3RfZGVl",
            "cF9kZXBlbmRlbmNpZXMvZmlsZTEyNC5wcm90bxoodW5pdHRlc3RfZGVlcF9k",
            "ZXBlbmRlbmNpZXMvZmlsZTEyMy5wcm90bxoodW5pdHRlc3RfZGVlcF9kZXBl",
            "bmRlbmNpZXMvZmlsZTIzMS5wcm90bxoodW5pdHRlc3RfZGVlcF9kZXBlbmRl",
            "bmNpZXMvZmlsZTIzMC5wcm90bxondW5pdHRlc3RfZGVlcF9kZXBlbmRlbmNp",
            "ZXMvZmlsZTI1LnByb3RvGid1bml0dGVzdF9kZWVwX2RlcGVuZGVuY2llcy9m",
            "aWxlMTYucHJvdG8aJ3VuaXR0ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGUy",
            "MC5wcm90bxomdW5pdHRlc3RfZGVlcF9kZXBlbmRlbmNpZXMvZmlsZTgucHJv",
            "dG8aKHVuaXR0ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGUyODAucHJvdG8a",
            "KHVuaXR0ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGUzNDIucHJvdG8aKHVu",
            "aXR0ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGUyODgucHJvdG8aKHVuaXR0",
            "ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGUzMDkucHJvdG8aKHVuaXR0ZXN0",
            "X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGUzMzEucHJvdG8aKHVuaXR0ZXN0X2Rl",
            "ZXBfZGVwZW5kZW5jaWVzL2ZpbGUzMzAucHJvdG8aKHVuaXR0ZXN0X2RlZXBf",
            "ZGVwZW5kZW5jaWVzL2ZpbGUzMzgucHJvdG8aKHVuaXR0ZXN0X2RlZXBfZGVw",
            "ZW5kZW5jaWVzL2ZpbGUyNzQucHJvdG8aKHVuaXR0ZXN0X2RlZXBfZGVwZW5k",
            "ZW5jaWVzL2ZpbGUyNzUucHJvdG8aJnVuaXR0ZXN0X2RlZXBfZGVwZW5kZW5j",
            "aWVzL2ZpbGUzLnByb3RvGih1bml0dGVzdF9kZWVwX2RlcGVuZGVuY2llcy9m",
            "aWxlMzM1LnByb3RvGih1bml0dGVzdF9kZWVwX2RlcGVuZGVuY2llcy9maWxl",
            "MzI2LnByb3RvGih1bml0dGVzdF9kZWVwX2RlcGVuZGVuY2llcy9maWxlMzAw",
            "LnByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::UnittestDeepDependencies.File14Reflection.Descriptor, global::UnittestDeepDependencies.File24Reflection.Descriptor, global::UnittestDeepDependencies.File124Reflection.Descriptor, global::UnittestDeepDependencies.File123Reflection.Descriptor, global::UnittestDeepDependencies.File231Reflection.Descriptor, global::UnittestDeepDependencies.File230Reflection.Descriptor, global::UnittestDeepDependencies.File25Reflection.Descriptor, global::UnittestDeepDependencies.File16Reflection.Descriptor, global::UnittestDeepDependencies.File20Reflection.Descriptor, global::UnittestDeepDependencies.File8Reflection.Descriptor, global::UnittestDeepDependencies.File280Reflection.Descriptor, global::UnittestDeepDependencies.File342Reflection.Descriptor, global::UnittestDeepDependencies.File288Reflection.Descriptor, global::UnittestDeepDependencies.File309Reflection.Descriptor, global::UnittestDeepDependencies.File331Reflection.Descriptor, global::UnittestDeepDependencies.File330Reflection.Descriptor, global::UnittestDeepDependencies.File338Reflection.Descriptor, global::UnittestDeepDependencies.File274Reflection.Descriptor, global::UnittestDeepDependencies.File275Reflection.Descriptor, global::UnittestDeepDependencies.File3Reflection.Descriptor, global::UnittestDeepDependencies.File335Reflection.Descriptor, global::UnittestDeepDependencies.File326Reflection.Descriptor, global::UnittestDeepDependencies.File300Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
