// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: csharp/protos/unittest_deep_dependencies/file73.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace UnittestDeepDependencies {

  /// <summary>Holder for reflection information generated from csharp/protos/unittest_deep_dependencies/file73.proto</summary>
  public static partial class File73Reflection {

    #region Descriptor
    /// <summary>File descriptor for csharp/protos/unittest_deep_dependencies/file73.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static File73Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVjc2hhcnAvcHJvdG9zL3VuaXR0ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2Zp",
            "bGU3My5wcm90bxIadW5pdHRlc3RfZGVlcF9kZXBlbmRlbmNpZXMaJnVuaXR0",
            "ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGU3LnByb3RvGid1bml0dGVzdF9k",
            "ZWVwX2RlcGVuZGVuY2llcy9maWxlMTQucHJvdG8aJ3VuaXR0ZXN0X2RlZXBf",
            "ZGVwZW5kZW5jaWVzL2ZpbGUyMS5wcm90bxomdW5pdHRlc3RfZGVlcF9kZXBl",
            "bmRlbmNpZXMvZmlsZTMucHJvdG8aJnVuaXR0ZXN0X2RlZXBfZGVwZW5kZW5j",
            "aWVzL2ZpbGU5LnByb3RvGid1bml0dGVzdF9kZWVwX2RlcGVuZGVuY2llcy9m",
            "aWxlMjUucHJvdG8aJ3VuaXR0ZXN0X2RlZXBfZGVwZW5kZW5jaWVzL2ZpbGUy",
            "NC5wcm90bxondW5pdHRlc3RfZGVlcF9kZXBlbmRlbmNpZXMvZmlsZTIyLnBy",
            "b3RvGiZ1bml0dGVzdF9kZWVwX2RlcGVuZGVuY2llcy9maWxlNi5wcm90bxon",
            "dW5pdHRlc3RfZGVlcF9kZXBlbmRlbmNpZXMvZmlsZTY0LnByb3RvYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::UnittestDeepDependencies.File7Reflection.Descriptor, global::UnittestDeepDependencies.File14Reflection.Descriptor, global::UnittestDeepDependencies.File21Reflection.Descriptor, global::UnittestDeepDependencies.File3Reflection.Descriptor, global::UnittestDeepDependencies.File9Reflection.Descriptor, global::UnittestDeepDependencies.File25Reflection.Descriptor, global::UnittestDeepDependencies.File24Reflection.Descriptor, global::UnittestDeepDependencies.File22Reflection.Descriptor, global::UnittestDeepDependencies.File6Reflection.Descriptor, global::UnittestDeepDependencies.File64Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
