#!/bin/bash
#
# This script sets up a Kokoro MacOS worker for running Protobuf tests

set -eux

export HOMEBREW_PREFIX=$(brew --prefix)

##
# Select Xcode version

##
# Select Xcode version
export DEVELOPER_DIR=/Applications/Xcode_13.3.1.app/Contents/Developer
sudo xcode-select -s "${DEVELOPER_DIR}"

##
# Select C/C++ compilers

export CC=gcc
export CXX=g++

##
# Install Python 2

if [[ "${KOKORO_INSTALL_PYTHON2:-}" == "yes" ]] ; then
    # Use python 2.
    eval "$(pyenv init -)"
    pyenv install -v -s 2.7.18 && pyenv global 2.7.18
fi

##
# Install Virtual Python Environment

if [[ "${KOKORO_INSTALL_VENV:-}" == "yes" ]] ; then
    python3 -m venv venv
    source venv/bin/activate
fi

##
# Install Tox

if [[ "${KOKORO_INSTALL_TOX:-}" == "yes" ]] ; then
  sudo python3 -m pip install --upgrade pip tox tox-pyenv
  pyenv install -v -s 3.5.10
  pyenv install -v -s 3.6.15
  pyenv install -v -s 3.7.13
  pyenv install -v -s 3.8.13
  pyenv install -v -s 3.9.13
fi

##
# Setup RVM
if [[ "${KOKORO_INSTALL_RVM:-}" == "yes" ]] ; then
    git config --global --add safe.directory $HOMEBREW_PREFIX/Library/Taps/homebrew/homebrew-cask
    git config --global --add safe.directory $HOMEBREW_PREFIX/Library/Taps/homebrew/homebrew-core
    git config --global --add safe.directory $HOMEBREW_PREFIX/Library/Taps/homebrew/homebrew-services
    sudo chown -R $(whoami) $HOME/.rvm/
fi

##
# Install external dependencies
brew install m4