load(":rust_proto_library_unit_test.bzl", "rust_proto_library_unit_test")

package(default_applicable_licenses = ["//third_party/protobuf:license"])

rust_proto_library_unit_test(name = "rust_proto_library_unit_test")
