source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.9'

install! 'cocoapods', :deterministic_uuids => false

if ENV['USE_FRAMEWORKS'] == 'YES' then
  use_frameworks!
end

target 'OSXCocoaPodsTester' do
  pod 'Protobuf', :path => '../../../..'
end
