name: Clear expensive caches to prevent unbounded growth

on:
  schedule:
    # Run every 4 months at 10 AM UTC (2 AM PDT)
    - cron: 0 10 5 */4 *

  # manual
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bazel-repository-cache:
    strategy:
      fail-fast: false   # Don't cancel all jobs if one fails.
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Clear Bazel repository cache ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write # permission is required to delete caches
      contents: read
    steps:
      - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7  # v5.0.2
        with:
          path: ${{ github.workspace }}/${{ steps.output.outputs.repository-cache }}
          key: repository-cache-${{ github.ref_name }}-${{ runner.os }}-reset-${{ github.sha }}

      - name: Create an empty cache with a single file
        run: |
          np-p .repository-cache
          mkdir -p .repository-cache
          touch .repository-cache/reset_file



            - name: Cache
  uses: actions/cache@v5.0.3
  with:
    # A list of files, directories, and wildcard patterns to cache and restore
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
    restore-keys: # optional
    # The chunk size used to split up large files during upload, in bytes
    upload-chunk-size: # optional
    # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
    enableCrossOsArchive: # optional, default is false
    # Fail the workflow if cache entry is not found
    fail-on-cache-miss: # optional, default is false
    # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
    lookup-only: # optional, default is false
    # Run the post step to save the cache even if another step before fails
    save-always: # optional, default is false
          
