name: Python Tests

on:
  workflow_call:
    inputs:
      continuous-run:
        required: true
        description: "Boolean string denoting whether this run is continuous --
          empty string for presubmit, non-empty string for continuous."
        type: string
      safe-checkout:
        required: true
        description: "The SHA key for the commit we want to run over"
        type: string
      continuous-prefix:
        required: true
        description: "The string continuous-only tests should be prefixed with when displaying test
          results."
        type: string


permissions:
  contents: read

jobs:
  linux:
    strategy:
      fail-fast: false   # Don't cancel all jobs if one fails.
      matrix:
        type: [ Pure, C++, aarch64 ]
        include:
          - type: Pure
            targets: //python/... //python:python_version_test
            flags: --define=use_fast_cpp_protos=false
          - type: C++
            targets: //python/... //python:python_version_test
            flags: --define=use_fast_cpp_protos=true
          - type: aarch64
            targets: //python/... //python:aarch64_test
            flags: --define=use_fast_cpp_protos=true --test_tag_filters=-conformance
            image: us-docker.pkg.dev/protobuf-build/containers/test/linux/emulation:8.0.1-aarch64-168f9c9d015a0fa16611e1e9eede796fe9bfbb69

    name: Linux ${{ matrix.type }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pending changes
        uses: protocolbuffers/protobuf-ci/checkout@v5
        with:
          ref: ${{ inputs.safe-checkout }}

      - name: Run Python 3.10
        if: ${{ matrix.type != 'aarch64' }}
        uses: protocolbuffers/protobuf-ci/bazel-docker@v5
        with:
          image: us-docker.pkg.dev/protobuf-build/containers/test/linux/python:9.0.0-3.10-7932bf8b25fb76a111e7257d151a6a58d5c3c671
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_linux/${{ matrix.type }}_3.10
          bash: >
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }} --test_env=KOKORO_PYTHON_VERSION $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;

      - name: Run Python 3.11
        if: ${{ matrix.type != 'aarch64' && inputs.continuous-prefix == '(Continuous)' }}
        uses: protocolbuffers/protobuf-ci/bazel-docker@v5
        with:
          image: us-docker.pkg.dev/protobuf-build/containers/test/linux/python:9.0.0-3.11-7932bf8b25fb76a111e7257d151a6a58d5c3c671
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_linux/${{ matrix.type }}_3.11
          bash: >
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }} --test_env=KOKORO_PYTHON_VERSION $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;

      - name: Run Python 3.12
        if: ${{ matrix.type != 'aarch64' && inputs.continuous-prefix == '(Continuous)' }}
        uses: protocolbuffers/protobuf-ci/bazel-docker@v5
        with:
          image: us-docker.pkg.dev/protobuf-build/containers/test/linux/python:9.0.0-3.12-7932bf8b25fb76a111e7257d151a6a58d5c3c671
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_linux/${{ matrix.type }}_3.12
          bash: >
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }} --test_env=KOKORO_PYTHON_VERSION $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;

      - name: Run Python 3.13
        if: ${{ matrix.type != 'aarch64' && inputs.continuous-prefix == '(Continuous)' }}
        uses: protocolbuffers/protobuf-ci/bazel-docker@v5
        with:
          image: us-docker.pkg.dev/protobuf-build/containers/test/linux/python:9.0.0-3.13-7932bf8b25fb76a111e7257d151a6a58d5c3c671
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_linux/${{ matrix.type }}_3.13
          bash: >
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }} --test_env=KOKORO_PYTHON_VERSION $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;

      - name: Run Python 3.14
        if: ${{ matrix.type != 'aarch64' }}
        uses: protocolbuffers/protobuf-ci/bazel-docker@v5
        with:
          image: us-docker.pkg.dev/protobuf-build/containers/test/linux/python:9.0.0-3.14-7932bf8b25fb76a111e7257d151a6a58d5c3c671
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_linux/${{ matrix.type }}_3.14
          bash: >
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }} --test_env=KOKORO_PYTHON_VERSION $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;

      - name: Run aarch64
        if: ${{ matrix.type == 'aarch64' }}
        uses: protocolbuffers/protobuf-ci/bazel-docker@v5
        with:
          image: ${{ matrix.image }}
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_linux/${{ matrix.type }}_aarch64
          bash: >
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }} --test_env=KOKORO_PYTHON_VERSION $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;


  macos:
    strategy:
      fail-fast: false   # Don't cancel all jobs if one fails.
      matrix:
        type: [ Pure, C++]
        include:
          - type: Pure
            targets: //python/... //python:python_version_test
          - type: C++
            targets: //python/... //python:python_version_test
            flags: --define=use_fast_cpp_protos=true

    name: MacOS ${{ matrix.type }}
    runs-on: macos-14
    steps:
      - name: Checkout pending changes
        uses: protocolbuffers/protobuf-ci/checkout@v5
        with:
          ref: ${{ inputs.safe-checkout }}

      # Python 3.12
      - name: Pin Python 3.12
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: 'python/requirements.txt'
      - name: Validate version 3.12
        run: python3 --version | grep 3.12 || (echo "Invalid Python version - $(python3 --version)" && exit 1)
      - name: Run tests 3.12
        uses: protocolbuffers/protobuf-ci/bazel@v5
        env:
          KOKORO_PYTHON_VERSION: "3.12"
        with:
          version: 9.0.0 # Bazel version
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_macos/${{ matrix.type }}_3.12
          bash: >-
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }}
            --test_env=KOKORO_PYTHON_VERSION=3.12
            --macos_minimum_os=12.0 $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;

      # Python 3.13
      - name: Pin Python 3.13
        if: ${{ inputs.continuous-prefix == '(Continuous)' }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: 'python/requirements.txt'
      - name: Validate version 3.13
        if: ${{ inputs.continuous-prefix == '(Continuous)' }}
        run: python3 --version | grep 3.13 || (echo "Invalid Python version - $(python3 --version)" && exit 1)
      - name: Run tests 3.13
        if: ${{ inputs.continuous-prefix == '(Continuous)' }}
        uses: protocolbuffers/protobuf-ci/bazel@v5
        env:
          KOKORO_PYTHON_VERSION: "3.13"
        with:
          version: 9.0.0 # Bazel version
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_macos/${{ matrix.type }}_3.13
          bash: >-
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }}
            --test_env=KOKORO_PYTHON_VERSION=3.13
            --macos_minimum_os=12.0 $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;

      # Python 3.14
      - name: Pin Python 3.14
        if: ${{ inputs.continuous-prefix == '(Continuous)' }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.14"
          cache: pip
          cache-dependency-path: 'python/requirements.txt'
      - name: Validate version 3.14
        if: ${{ inputs.continuous-prefix == '(Continuous)' }}
        run: python3 --version | grep 3.14 || (echo "Invalid Python version - $(python3 --version)" && exit 1)
      - name: Run tests 3.14
        if: ${{ inputs.continuous-prefix == '(Continuous)' }}
        uses: protocolbuffers/protobuf-ci/bazel@v5
        env:
          KOKORO_PYTHON_VERSION: "3.14"
        with:
          version: 9.0.0 # Bazel version
          credentials: ${{ secrets.GAR_SERVICE_ACCOUNT }}
          bazel-cache: python_macos/${{ matrix.type }}_3.14
          bash: >-
            bazel --batch test ${{ matrix.targets }} ${{ matrix.flags }}
            --test_env=KOKORO_PYTHON_VERSION=3.14
            --macos_minimum_os=12.0 $BAZEL_FLAGS;
            bazel --batch clean --expunge --async;
